### ISSUE TITLE
IABHELPER crash when activity is destroyed before helper dismissed

### ISSUE THREAD

**Issue by holyspidoo** [googlesamples/android-play-billing#13] opened 2016-04-14 14:02 UTC
I have found adding these two lines fix the problem. Useful if your app is aggresively killing activities for out of memory reasons.

Thoughts?

```
int queryPurchases(Inventory inv, String itemType) throws JSONException, RemoteException {
        // Query purchases

        // This is a check to see if activity was destroyed before helper is dismissed
        if(mDisposed) return IABHELPER_UNKNOWN_ERROR;
        if(mContext == null) return IABHELPER_UNKNOWN_ERROR;


        logDebug("Querying owned items, item type: " + itemType);
        ...
```

**Comment by shlusiak** [comment] 2016-04-25 23:53
This doesn't completely fix the race condition in the code. The problem is the call to context.getPackageName() which is run from a secondary thread, while the main thread can set context to null by calling dispose(). 

I have changed my copy of the code to store mContext in a local variable before checking if it is null to avoid the main thread setting it to null in the do-loop. 

```
int queryPurchases(Inventory inv, String itemType) throws JSONException, RemoteException {
	Context context = mContext;
	if (mDisposed || context == null)
		return IABHELPER_VERIFICATION_FAILED;

[...]

Bundle ownedItems = mService.getPurchases(3, context.getPackageName(),
                    itemType, continueToken);
```

Does anyone have code how to do this properly? I'm not impressed with the example's handling of concurrency.

**Comment by xingstarx** [comment] 2016-04-29 08:37
why not fix use this:
`if(isEmpty()){
            logError("Our service and/or our context are null.  Exiting.");
            return IABHELPER_UNKNOWN_ERROR;
        }`

`public boolean isEmpty() {
        if (mService == null || mContext == null) {
            return true;
        }
        return false;
    }`

**Comment by rpattabi** [comment] 2016-07-23 06:20
I see a somewhat recent fix to race condition which adds `IabHelper::disposeWhenFinished()`.

```        
in onDestroy()
if (mIabHelper != null) {
    mIabHelper.disposeWhenFinished();
    mIabHelper = null;
}
```
May be it fixes the same issue reported here.

**Comment by netomarin** [comment] 2017-06-01 03:39
Hi
This is fixed by the change mentioned by @rpattabi.

Thanks

**Closed by netomarin** 2017-06-01 03:39 UTC
