### ISSUE TITLE
mServices = null in some situations

### ISSUE THREAD

**Issue by maxim-yudin** [googlesamples/android-play-billing#21] opened 2016-06-08 10:32 UTC
do {
            logDebug("Calling getPurchases with continuation token: " + continueToken);
            Bundle ownedItems = mService.getPurchases(3, mContext.getPackageName(),
                    itemType, continueToken);

IabHelper.queryPurchases (IabHelper.java:840)
IabHelper.queryInventory (IabHelper.java:611)
IabHelper$2.run (IabHelper.java:669)

**Comment by maxim-yudin** [comment] 2016-06-08 10:33
I think this solution is https://github.com/googlesamples/android-play-billing/pull/19/files

**Comment by netomarin** [comment] 2017-06-01 03:38
This a duplicate of https://github.com/googlesamples/android-play-billing/issues/45
Will update in the other issue.

Thanks

**Closed by netomarin** 2017-06-01 03:38 UTC
Labels: duplicate
