### ISSUE TITLE
billingClient.querySkuDetailsAsync - doesn't return status of item (active/inactive)

### ISSUE THREAD

**Issue by wheelergames** [googlesamples/android-play-billing#192] opened 2019-04-29 10:29 UTC
I am trying to use billingClient.querySkuDetailsAsync() and I want to know if items are active or not so I can display them accordingly i.e. ghost/grey them out and have a coming soon written near it.

But looking in SkuDetail there is nothing that gives me the status of an item?

**Comment by isaidamier** [comment] 2019-05-14 21:01
Hi! Thanks for reaching out. `billingClient.querySkuDetailsAsync()` only returns your active SKUs by design. The feature is such that SKUs that you deactivate in the Google Play Console are SKUs that you don't want your users to see or be aware of. One example might be a product you used to sell but decided to discontinue.

**Comment by isaidamier** [comment] 2019-05-14 21:09
closing as resolved. If you believe there is still an issue, please provide more details for your use-case and re-open. Thanks!

**Closed by isaidamier** 2019-05-14 21:09 UTC

**Comment by wheelergames** [comment] 2019-05-14 22:41
I understand that this was designed this way, but is there any issue to adding skus? Or maybe having a new endpoint?

As it is, if I have a new in app product then I have to do a code release. You could argue that I'd potentially have to do that to supply the new feature anyway, I guess, but I want to also list the 'coming soon' features that people can pay for in the future.

I've done a work around at the moment, using my own server where I call the google publishing api, but it's a bit annoying that I've almost got all the info from the this library, but I'm one bit of info short.

Thanks for replying.

**Comment by 3c71** [comment] 2020-05-12 06:37
I use billingClient.querySkuDetailsAsync() and I do receive inactive sku as well. So if I want to disable a particular sku, I have to do a code release !?

Doesn't seem to be designed to return only active ones sadly.
