### ISSUE TITLE
launchPurchaseFlow for a subscription will return an error, but still charge the user for the subscription.

### ISSUE THREAD

**Issue by ssawchenko** [googlesamples/android-play-billing#89] opened 2017-09-28 21:01 UTC
Previously I had been running subscription purchases through the IABHelper.java's - `launchPurchaseFlow`. I did not realize that this was actually running a purchase for `ITEM_TYPE_INAPP` items. Regardless, this used to function correctly, and the subscriptions were being purchased correctly.

This week I got a report from my client that there was an issue with subscription purchases. It seems that now purchasing a subscription while using launchPurchaseFlow will return an error (_"IAB returned null purchaseData or dataSignature"_), despite the user actually being charged for the subscription. I now understand that I should be calling `launchSubscriptionPurchaseFlow` (and have updated my project accordingly), however, this seems like a bug (having an error returned while still being charged for the item) that should be addressed.

I realize that this may actually be a bug on the server side of the equation, but figured I would post here to see if this has been documented already, before creating an issue on issuetracker.

**Comment by gorgon** [comment] 2017-09-28 21:11
I am sorry, but which library are you talking about?
launchSubscriptionPurchaseFlow doesn't exist inside Google's Play billing library.
You should always call [launchPurchaseFlow](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#launchBillingFlow) and just change the arguments for subs and inapps.
Please see [here](https://developer.android.com/training/in-app-billing/purchase-iab-products.html) for more details.

**Comment by ssawchenko** [comment] 2017-09-28 21:16
Whoops, sorry. When we originally implemented our IAB we used the "Trial Drive Samples" as a template, so the code I am referencing is from that project's utils:

https://github.com/googlesamples/android-play-billing/tree/master/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/util

Digging into *that* source it would seem that it is calling: IInAppBillingService.getBuyIntent 
```
buyIntentBundle = mService.getBuyIntent(3, mContext.getPackageName(), sku, itemType, extraData);
```
where sku would correspond to a subscription item, but the itemType would (incorrectly) be `inapp`.

**Comment by ssawchenko** [comment] 2017-09-28 21:18
So I guess the issue here is that calling `launchPurchaseFlow` for a subscription item, but using the `inapp` item type is actually succeeding in charging the customer for the subscription, despite it returning an error.

**Comment by d-schmidt** [comment] 2017-10-25 19:00
These samples and moderation here are a mess. Why do the Google employees here not know and recognize the TrivalDrive v1 example anymore? It was the recommended implementation for years and  until a few weeks ago! It is like it vanished from the hive minds memory.

We are trying to give you money Google!

**The official docs recommended IABHelper.java.**

@gorgon I don't get your confusion. In his very first line @ssawchenko  says `IABHelper.java`. He clearly is using the 'old' TrivalDrive v1. I assume you didn't start working on this last week.

It is like #45 
In June: @dec1: 'there is an NPE bug in the TrivalDrive example'
@netomarin: 'we will look into it'
August: @netomarin: 'still looking into it'
End August: @gorgon 'It is not a bug. You need to do a retry as shown in TrivalDrive v2'
October: @netomarin: 'It is not a bug in the sample.'

What is going on? It is a bug in the V1 sample. Retrying the BillingClient is no solution. But I guess pretending the recommended method of the last years doesn't exsist, is easier.

Why is this so frustrating.

**Comment by netomarin** [comment] 2017-10-25 23:40
@ssawchenko Thanks for you report. With your last message the situation is clear. I will forward this internally to check what is happening.
Sorry for taking to long to check this issue, and I'll get back to this thread when we have an answer.

@d-schmidt Sorry for your frustration, but we are here to try to help you. Of course we want to provide the best support we can, and let's to understand your frustration.

Our docs mention IABHelper on a single point, the [Selling In-app Products](https://developer.android.com/training/in-app-billing/index.html) training class. This section was kept for legacy purpose, because we didn't remove TrivialDrive v1. But I agree that is probably confusing developers.
To improve, I've already filled a but to add a note to this page, making the communication more clear.

**The Play Billing Library is our recommended solution** if you are a Java / Kotlin developer, but if you are developing using a framework in any other language, you might need to use the AIDL interface, and we kept the Trivial Drive v1 because is a sample where you can see (a canonical reference) how to interact with In-app Billing Service using the AIDL.
At some time in the future, we won't support the AIDL anymore and Trivial Drive v1 will be removed, but until there, we will keep the sample. But, it won't be updated or extended, unless is really necessary.

@d-schmidt I hope I have answered your question, and if you still have further questions, feel free to reach me out or open a bug on our [public bug tracker](https://issuetracker.google.com/issues?q=componentid:311487). We are doing our best to address all issues and solve the problems, and we appreciate with you comprehension.

Cheers,
Neto

**Comment by ssawchenko** [comment] 2017-10-26 18:28
@netomarin Thank you for the reply and for following up on this. I have had IAB implemented for over a year now (so before the Play Billing Library was released), and unfortunately have not had time allotted to me from the client to refactor/update to use the new library. I will mention it to them that the AIDL method is now deprecated and that we should look into moving over to the new library.

Cheers!

**Comment by d-schmidt** [comment] 2017-10-27 15:16
> [The sample still contains some rare bugs] But, it won't be updated

This is the announcement you should also add to the [TrivialDrive README](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/README.md).  
This is not helpful at all but at least we know for sure.

Like @ssawchenko I'm one of the thousands of devs who have implemented billing using the provided IABHelper from the doc sample during the last years.  
The difference between me and @ssawchenko is: I already gave up hope last week and re-implemented billing using the new BillingClient. I've got the adavantage of my app being my own under my control. Now I have to test something again I knew to work fine 99% of the time. I have to hope I didn't create new bugs in my implementation, the BillingClient doesn't have bugs and the old bugs are gone. And all the fuzz because app crashed hard for some random users if their device killed the billing service while the IABHelper was waiting for the response.

/rant

Thanks for the clear response @netomarin

One last positive note: the new docs mention a new(?) and easier way to test billing using test accounts.

**Comment by ssawchenko** [comment] 2017-10-27 18:27
Edit: Whoops, bumped the wrong button, didn't mean to close this issue.

> One last positive note: the new docs mention a new(?) and easier way to test billing using test accounts.
I'm just glad I can create test subscriptions that last a day instead of a week now - testing subscriptions originally was pretty much the worst.

Anyhoot, also /rant - I don't want to derail the topic :)

**Comment by pfmaggi** [comment] 2019-01-10 12:16
Please refer to ClassyTaxy And Trivial Drive 2.

Closing as obsolete.

Please reopen if you think this issue is still relevant.

**Closed by pfmaggi** 2019-01-10 12:16 UTC
