### ISSUE TITLE
PurchaseUpdateListener issue

### ISSUE THREAD

**Issue by umair6** [googlesamples/android-play-billing#116] opened 2018-01-18 13:06 UTC
Hi,

In following scenario where "onPurchasesUpdated" function does not get called.

Start inapp purhcase by pressing buy button. When Google Play purchase screen is displayed on screen, minimise app by pressing home button. Reopen app and you will see that Google Play purchase screen has disappeared without calling onPurchasesUpdated function. 

As per some requirements in my application, I am disabling few controllers which should be enabled once inapp flow is completed (success or fail). But this issue is causing some problems.

**Comment by umair6** [comment] 2018-01-18 13:09
@gorgon @cartland Please help.

**Comment by netomarin** [comment] 2018-02-28 22:12
@umair6 onPurchasesUpdated is called *only* if the purchase is processed.
The scenario you are describing, the purchased didn't happen, so there is nothing to be updated on onPurchasesUpdated.

You can implement some lifecycle controls to identify if the user started a purchase or just let the user keep using the app.

**Comment by huster001** [comment] 2018-07-19 07:37
It's not like @netomarin mentioned above. Try it like this:

launch the purchase flow and pay for it, then you will get a popup up dialog telling you that payment is successful.  Press home key and reopen your app, onPurchasesUpdated will not be called.

It's a bug!

**Comment by huster001** [comment] 2018-07-19 07:45
What I did to solve the problem is:

When the application switches to the front end.  call queryPurchases() to get the items owned and check if it contains the one you want to buy. If so, you can decicde the purchase is successful, otherwise, the purchase is canceled.

I had to do so because my UI logic depends on the purchase result.

**Comment by umair6** [comment] 2018-07-19 08:35
@huster001  I am doing exactly same to solve above issue.

**Comment by isaidamier** [comment] 2019-08-20 19:08
closing as resolved. Please reopen with additional detail if the problem resurfaces.

**Closed by isaidamier** 2019-08-20 19:08 UTC
Labels: play billing library
