### ISSUE TITLE
IInAppBillingService.getBuyIntent return null Bundle

### ISSUE THREAD

**Issue by xingstarx** [googlesamples/android-play-billing#37] opened 2016-09-13 06:53 UTC
I get some  crash reposting with this exception

``` java
java.lang.NullPointerException
        at io.vec.util.b.d.a(IabHelper.java:890)
        at io.vec.util.b.d.a(IabHelper.java:478)
        at io.vec.util.b.d.a(IabHelper.java:406)
```

in this repo, in this method 

```
public void launchPurchaseFlow(Activity act, String sku, String itemType, List<String> oldSkus,
            int requestCode, OnIabPurchaseFinishedListener listener, String extraData)
        throws IabAsyncInProgressException { }
```

we called 

```
 buyIntentBundle = mService.getBuyIntent(3, mContext.getPackageName(), sku, itemType,
                        extraData);
```

 and buyIntentBundle is null 

can you help me?

and I can't reproduce it.

**Comment by netomarin** [comment] 2017-06-01 03:26
@xingstarx 
It seems that the IABHelper were not able to create the bundle due to some parameter error.
Did you checked the sku and item type?

Have you ever reproduced this error?

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.

**Closed by netomarin** 2017-06-01 03:26 UTC
